# Generated by Django 3.0.3 on 2020-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sent_level', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'sentence',
                'managed': True,
            },
        ),
    ]
